apiVersion: v1
kind: Service
metadata:
  name: ad
  labels:
    app: ad
    service: ad
spec:
  clusterIP: None
  ports:
  - port: 8089
    targetPort: 8089
    name: arpc-ad
    protocol: UDP
  selector:
    app: ad
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-ad
  labels:
    account: ad
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  labels:
    app: ad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      serviceAccountName: onlineboutique-ad
      containers:
      - name: ad
        image: appnetorg/onlineboutique-arpc:latest
        command:
        - /app/onlineboutique
        args:
        - ad
        imagePullPolicy: Always
        ports:
        - containerPort: 8089
        env:
        - name: LOG_LEVEL
          value: debug
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command:
        - /app/proxy
        securityContext:
          runAsUser: 1337
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: LOG_LEVEL
          value: debug
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
        - /bin/sh
        - -c
        - bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ad-pv
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: ad-storage
  hostPath:
    path: /data/volumes/ad-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ad-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ad-storage
  resources:
    requests:
      storage: 1Gi
