apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    app: email
    service: email
spec:
  clusterIP: None
  ports:
  - port: 11006
    targetPort: 11006
    name: arpc-email
    protocol: UDP
  selector:
    app: email
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-email
  labels:
    account: email
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      serviceAccountName: onlineboutique-email
      containers:
      - name: email
        image: appnetorg/onlineboutique-arpc:latest
        command:
        - /app/onlineboutique
        args:
        - email
        imagePullPolicy: Always
        ports:
        - containerPort: 11006
        env:
        - name: LOG_LEVEL
          value: debug
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command:
        - /app/proxy
        securityContext:
          runAsUser: 1337
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: LOG_LEVEL
          value: debug
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
        - /bin/sh
        - -c
        - bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: email-pv
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: email-storage
  hostPath:
    path: /data/volumes/email-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: email-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: email-storage
  resources:
    requests:
      storage: 1Gi
