apiVersion: v1
kind: Service
metadata:
  name: productcatalog
  labels:
    app: productcatalog
    service: productcatalog
spec:
  clusterIP: None
  ports:
  - port: 8082
    targetPort: 8082
    name: arpc-productcatalog
    protocol: UDP
  selector:
    app: productcatalog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-productcatalog
  labels:
    account: productcatalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalog
  labels:
    app: productcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productcatalog
  template:
    metadata:
      labels:
        app: productcatalog
    spec:
      serviceAccountName: onlineboutique-productcatalog
      containers:
      - name: productcatalog
        image: appnetorg/onlineboutique-arpc:latest
        command:
        - /app/onlineboutique
        args:
        - productcatalog
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: LOG_LEVEL
          value: debug
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command:
        - /app/proxy
        securityContext:
          runAsUser: 1337
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: LOG_LEVEL
          value: debug
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
        - /bin/sh
        - -c
        - bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: productcatalog-pv
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: productcatalog-storage
  hostPath:
    path: /data/volumes/productcatalog-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: productcatalog-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: productcatalog-storage
  resources:
    requests:
      storage: 1Gi
