apiVersion: v1
kind: Service
metadata:
  name: recommendation
  labels:
    app: recommendation
    service: recommendation
spec:
  clusterIP: None
  ports:
  - port: 8088
    targetPort: 8088
    name: arpc-recommendation
    protocol: UDP
  selector:
    app: recommendation
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onlineboutique-recommendation
  labels:
    account: recommendation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  labels:
    app: recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      serviceAccountName: onlineboutique-recommendation
      containers:
      - name: recommendation
        image: appnetorg/onlineboutique-arpc:latest
        command:
        - /app/onlineboutique
        args:
        - recommendation
        imagePullPolicy: Always
        ports:
        - containerPort: 8088
        env:
        - name: LOG_LEVEL
          value: info
      - name: symphony-proxy
        image: appnetorg/symphony-proxy:latest
        command:
        - /app/proxy
        securityContext:
          runAsUser: 1337
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        env:
        - name: LOG_LEVEL
          value: info
      initContainers:
      - name: set-iptables
        image: appnetorg/symphony-proxy-init-container:latest
        command:
        - /bin/sh
        - -c
        - bash /apply_symphony_iptables.sh
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: recommendation-pv
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: recommendation-storage
  hostPath:
    path: /data/volumes/recommendation-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recommendation-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: recommendation-storage
  resources:
    requests:
      storage: 1Gi
