// Code generated by protoc-gen-arpc. DO NOT EDIT.
package onlineboutique

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
	"github.com/appnet-org/arpc/pkg/rpc/element"
)

// Service IDs
const (
	ServiceID_CartService           = 1
	ServiceID_RecommendationService = 2
	ServiceID_ProductCatalogService = 3
	ServiceID_ShippingService       = 4
	ServiceID_CurrencyService       = 5
	ServiceID_PaymentService        = 6
	ServiceID_EmailService          = 7
	ServiceID_CheckoutService       = 8
	ServiceID_AdService             = 9
)

// Service name <-> ID mappings
var serviceNameToID = map[string]uint32{
	"CartService":           ServiceID_CartService,
	"RecommendationService": ServiceID_RecommendationService,
	"ProductCatalogService": ServiceID_ProductCatalogService,
	"ShippingService":       ServiceID_ShippingService,
	"CurrencyService":       ServiceID_CurrencyService,
	"PaymentService":        ServiceID_PaymentService,
	"EmailService":          ServiceID_EmailService,
	"CheckoutService":       ServiceID_CheckoutService,
	"AdService":             ServiceID_AdService,
}

var serviceIDToName = map[uint32]string{
	ServiceID_CartService:           "CartService",
	ServiceID_RecommendationService: "RecommendationService",
	ServiceID_ProductCatalogService: "ProductCatalogService",
	ServiceID_ShippingService:       "ShippingService",
	ServiceID_CurrencyService:       "CurrencyService",
	ServiceID_PaymentService:        "PaymentService",
	ServiceID_EmailService:          "EmailService",
	ServiceID_CheckoutService:       "CheckoutService",
	ServiceID_AdService:             "AdService",
}

// Method IDs for CartService
const (
	CartService_MethodID_AddItem   = 1
	CartService_MethodID_GetCart   = 2
	CartService_MethodID_EmptyCart = 3
)

// Method name <-> ID mappings for CartService
var CartService_methodNameToID = map[string]uint32{
	"AddItem":   CartService_MethodID_AddItem,
	"GetCart":   CartService_MethodID_GetCart,
	"EmptyCart": CartService_MethodID_EmptyCart,
}

var CartService_methodIDToName = map[uint32]string{
	CartService_MethodID_AddItem:   "AddItem",
	CartService_MethodID_GetCart:   "GetCart",
	CartService_MethodID_EmptyCart: "EmptyCart",
}

// CartServiceClient is the client API for CartService service.
type CartServiceClient interface {
	AddItem(ctx context.Context, req *AddItemRequest) (*Empty, error)
	GetCart(ctx context.Context, req *GetCartRequest) (*Cart, error)
	EmptyCart(ctx context.Context, req *EmptyCartRequest) (*Empty, error)
}

type arpcCartServiceClient struct {
	client *rpc.Client
}

func NewCartServiceClient(client *rpc.Client) CartServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("CartService", ServiceID_CartService, CartService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcCartServiceClient{client: client}
}

func (c *arpcCartServiceClient) AddItem(ctx context.Context, req *AddItemRequest) (*Empty, error) {
	resp := new(Empty)
	if err := c.client.Call(ctx, "CartService", "AddItem", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcCartServiceClient) GetCart(ctx context.Context, req *GetCartRequest) (*Cart, error) {
	resp := new(Cart)
	if err := c.client.Call(ctx, "CartService", "GetCart", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcCartServiceClient) EmptyCart(ctx context.Context, req *EmptyCartRequest) (*Empty, error) {
	resp := new(Empty)
	if err := c.client.Call(ctx, "CartService", "EmptyCart", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type CartServiceServer interface {
	AddItem(ctx context.Context, req *AddItemRequest) (*Empty, context.Context, error)
	GetCart(ctx context.Context, req *GetCartRequest) (*Cart, context.Context, error)
	EmptyCart(ctx context.Context, req *EmptyCartRequest) (*Empty, context.Context, error)
}

func RegisterCartServiceServer(s *rpc.Server, srv CartServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "CartService",
		ServiceID:   ServiceID_CartService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			CartService_MethodID_AddItem: {
				MethodName: "AddItem",
				MethodID:   CartService_MethodID_AddItem,
				Handler:    _CartService_AddItem_Handler,
			},
			CartService_MethodID_GetCart: {
				MethodName: "GetCart",
				MethodID:   CartService_MethodID_GetCart,
				Handler:    _CartService_GetCart_Handler,
			},
			CartService_MethodID_EmptyCart: {
				MethodName: "EmptyCart",
				MethodID:   CartService_MethodID_EmptyCart,
				Handler:    _CartService_EmptyCart_Handler,
			},
		},
	}, srv)
}

func _CartService_AddItem_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(AddItemRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CartServiceServer).AddItem(ctx, req.Payload.(*AddItemRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _CartService_GetCart_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(GetCartRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CartServiceServer).GetCart(ctx, req.Payload.(*GetCartRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _CartService_EmptyCart_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(EmptyCartRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CartServiceServer).EmptyCart(ctx, req.Payload.(*EmptyCartRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for RecommendationService
const (
	RecommendationService_MethodID_ListRecommendations = 1
)

// Method name <-> ID mappings for RecommendationService
var RecommendationService_methodNameToID = map[string]uint32{
	"ListRecommendations": RecommendationService_MethodID_ListRecommendations,
}

var RecommendationService_methodIDToName = map[uint32]string{
	RecommendationService_MethodID_ListRecommendations: "ListRecommendations",
}

// RecommendationServiceClient is the client API for RecommendationService service.
type RecommendationServiceClient interface {
	ListRecommendations(ctx context.Context, req *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
}

type arpcRecommendationServiceClient struct {
	client *rpc.Client
}

func NewRecommendationServiceClient(client *rpc.Client) RecommendationServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("RecommendationService", ServiceID_RecommendationService, RecommendationService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcRecommendationServiceClient{client: client}
}

func (c *arpcRecommendationServiceClient) ListRecommendations(ctx context.Context, req *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	resp := new(ListRecommendationsResponse)
	if err := c.client.Call(ctx, "RecommendationService", "ListRecommendations", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type RecommendationServiceServer interface {
	ListRecommendations(ctx context.Context, req *ListRecommendationsRequest) (*ListRecommendationsResponse, context.Context, error)
}

func RegisterRecommendationServiceServer(s *rpc.Server, srv RecommendationServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "RecommendationService",
		ServiceID:   ServiceID_RecommendationService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			RecommendationService_MethodID_ListRecommendations: {
				MethodName: "ListRecommendations",
				MethodID:   RecommendationService_MethodID_ListRecommendations,
				Handler:    _RecommendationService_ListRecommendations_Handler,
			},
		},
	}, srv)
}

func _RecommendationService_ListRecommendations_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(ListRecommendationsRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(RecommendationServiceServer).ListRecommendations(ctx, req.Payload.(*ListRecommendationsRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for ProductCatalogService
const (
	ProductCatalogService_MethodID_ListProducts   = 1
	ProductCatalogService_MethodID_GetProduct     = 2
	ProductCatalogService_MethodID_SearchProducts = 3
)

// Method name <-> ID mappings for ProductCatalogService
var ProductCatalogService_methodNameToID = map[string]uint32{
	"ListProducts":   ProductCatalogService_MethodID_ListProducts,
	"GetProduct":     ProductCatalogService_MethodID_GetProduct,
	"SearchProducts": ProductCatalogService_MethodID_SearchProducts,
}

var ProductCatalogService_methodIDToName = map[uint32]string{
	ProductCatalogService_MethodID_ListProducts:   "ListProducts",
	ProductCatalogService_MethodID_GetProduct:     "GetProduct",
	ProductCatalogService_MethodID_SearchProducts: "SearchProducts",
}

// ProductCatalogServiceClient is the client API for ProductCatalogService service.
type ProductCatalogServiceClient interface {
	ListProducts(ctx context.Context, req *EmptyUser) (*ListProductsResponse, error)
	GetProduct(ctx context.Context, req *GetProductRequest) (*Product, error)
	SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, error)
}

type arpcProductCatalogServiceClient struct {
	client *rpc.Client
}

func NewProductCatalogServiceClient(client *rpc.Client) ProductCatalogServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("ProductCatalogService", ServiceID_ProductCatalogService, ProductCatalogService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcProductCatalogServiceClient{client: client}
}

func (c *arpcProductCatalogServiceClient) ListProducts(ctx context.Context, req *EmptyUser) (*ListProductsResponse, error) {
	resp := new(ListProductsResponse)
	if err := c.client.Call(ctx, "ProductCatalogService", "ListProducts", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcProductCatalogServiceClient) GetProduct(ctx context.Context, req *GetProductRequest) (*Product, error) {
	resp := new(Product)
	if err := c.client.Call(ctx, "ProductCatalogService", "GetProduct", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcProductCatalogServiceClient) SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, error) {
	resp := new(SearchProductsResponse)
	if err := c.client.Call(ctx, "ProductCatalogService", "SearchProducts", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ProductCatalogServiceServer interface {
	ListProducts(ctx context.Context, req *EmptyUser) (*ListProductsResponse, context.Context, error)
	GetProduct(ctx context.Context, req *GetProductRequest) (*Product, context.Context, error)
	SearchProducts(ctx context.Context, req *SearchProductsRequest) (*SearchProductsResponse, context.Context, error)
}

func RegisterProductCatalogServiceServer(s *rpc.Server, srv ProductCatalogServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "ProductCatalogService",
		ServiceID:   ServiceID_ProductCatalogService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			ProductCatalogService_MethodID_ListProducts: {
				MethodName: "ListProducts",
				MethodID:   ProductCatalogService_MethodID_ListProducts,
				Handler:    _ProductCatalogService_ListProducts_Handler,
			},
			ProductCatalogService_MethodID_GetProduct: {
				MethodName: "GetProduct",
				MethodID:   ProductCatalogService_MethodID_GetProduct,
				Handler:    _ProductCatalogService_GetProduct_Handler,
			},
			ProductCatalogService_MethodID_SearchProducts: {
				MethodName: "SearchProducts",
				MethodID:   ProductCatalogService_MethodID_SearchProducts,
				Handler:    _ProductCatalogService_SearchProducts_Handler,
			},
		},
	}, srv)
}

func _ProductCatalogService_ListProducts_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(EmptyUser)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(ProductCatalogServiceServer).ListProducts(ctx, req.Payload.(*EmptyUser))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _ProductCatalogService_GetProduct_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(GetProductRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(ProductCatalogServiceServer).GetProduct(ctx, req.Payload.(*GetProductRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _ProductCatalogService_SearchProducts_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(SearchProductsRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(ProductCatalogServiceServer).SearchProducts(ctx, req.Payload.(*SearchProductsRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for ShippingService
const (
	ShippingService_MethodID_GetQuote  = 1
	ShippingService_MethodID_ShipOrder = 2
)

// Method name <-> ID mappings for ShippingService
var ShippingService_methodNameToID = map[string]uint32{
	"GetQuote":  ShippingService_MethodID_GetQuote,
	"ShipOrder": ShippingService_MethodID_ShipOrder,
}

var ShippingService_methodIDToName = map[uint32]string{
	ShippingService_MethodID_GetQuote:  "GetQuote",
	ShippingService_MethodID_ShipOrder: "ShipOrder",
}

// ShippingServiceClient is the client API for ShippingService service.
type ShippingServiceClient interface {
	GetQuote(ctx context.Context, req *GetQuoteRequest) (*GetQuoteResponse, error)
	ShipOrder(ctx context.Context, req *ShipOrderRequest) (*ShipOrderResponse, error)
}

type arpcShippingServiceClient struct {
	client *rpc.Client
}

func NewShippingServiceClient(client *rpc.Client) ShippingServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("ShippingService", ServiceID_ShippingService, ShippingService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcShippingServiceClient{client: client}
}

func (c *arpcShippingServiceClient) GetQuote(ctx context.Context, req *GetQuoteRequest) (*GetQuoteResponse, error) {
	resp := new(GetQuoteResponse)
	if err := c.client.Call(ctx, "ShippingService", "GetQuote", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcShippingServiceClient) ShipOrder(ctx context.Context, req *ShipOrderRequest) (*ShipOrderResponse, error) {
	resp := new(ShipOrderResponse)
	if err := c.client.Call(ctx, "ShippingService", "ShipOrder", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ShippingServiceServer interface {
	GetQuote(ctx context.Context, req *GetQuoteRequest) (*GetQuoteResponse, context.Context, error)
	ShipOrder(ctx context.Context, req *ShipOrderRequest) (*ShipOrderResponse, context.Context, error)
}

func RegisterShippingServiceServer(s *rpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "ShippingService",
		ServiceID:   ServiceID_ShippingService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			ShippingService_MethodID_GetQuote: {
				MethodName: "GetQuote",
				MethodID:   ShippingService_MethodID_GetQuote,
				Handler:    _ShippingService_GetQuote_Handler,
			},
			ShippingService_MethodID_ShipOrder: {
				MethodName: "ShipOrder",
				MethodID:   ShippingService_MethodID_ShipOrder,
				Handler:    _ShippingService_ShipOrder_Handler,
			},
		},
	}, srv)
}

func _ShippingService_GetQuote_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(GetQuoteRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(ShippingServiceServer).GetQuote(ctx, req.Payload.(*GetQuoteRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _ShippingService_ShipOrder_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(ShipOrderRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(ShippingServiceServer).ShipOrder(ctx, req.Payload.(*ShipOrderRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for CurrencyService
const (
	CurrencyService_MethodID_GetSupportedCurrencies = 1
	CurrencyService_MethodID_Convert                = 2
)

// Method name <-> ID mappings for CurrencyService
var CurrencyService_methodNameToID = map[string]uint32{
	"GetSupportedCurrencies": CurrencyService_MethodID_GetSupportedCurrencies,
	"Convert":                CurrencyService_MethodID_Convert,
}

var CurrencyService_methodIDToName = map[uint32]string{
	CurrencyService_MethodID_GetSupportedCurrencies: "GetSupportedCurrencies",
	CurrencyService_MethodID_Convert:                "Convert",
}

// CurrencyServiceClient is the client API for CurrencyService service.
type CurrencyServiceClient interface {
	GetSupportedCurrencies(ctx context.Context, req *EmptyUser) (*GetSupportedCurrenciesResponse, error)
	Convert(ctx context.Context, req *CurrencyConversionRequest) (*Money, error)
}

type arpcCurrencyServiceClient struct {
	client *rpc.Client
}

func NewCurrencyServiceClient(client *rpc.Client) CurrencyServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("CurrencyService", ServiceID_CurrencyService, CurrencyService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcCurrencyServiceClient{client: client}
}

func (c *arpcCurrencyServiceClient) GetSupportedCurrencies(ctx context.Context, req *EmptyUser) (*GetSupportedCurrenciesResponse, error) {
	resp := new(GetSupportedCurrenciesResponse)
	if err := c.client.Call(ctx, "CurrencyService", "GetSupportedCurrencies", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcCurrencyServiceClient) Convert(ctx context.Context, req *CurrencyConversionRequest) (*Money, error) {
	resp := new(Money)
	if err := c.client.Call(ctx, "CurrencyService", "Convert", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type CurrencyServiceServer interface {
	GetSupportedCurrencies(ctx context.Context, req *EmptyUser) (*GetSupportedCurrenciesResponse, context.Context, error)
	Convert(ctx context.Context, req *CurrencyConversionRequest) (*Money, context.Context, error)
}

func RegisterCurrencyServiceServer(s *rpc.Server, srv CurrencyServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "CurrencyService",
		ServiceID:   ServiceID_CurrencyService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			CurrencyService_MethodID_GetSupportedCurrencies: {
				MethodName: "GetSupportedCurrencies",
				MethodID:   CurrencyService_MethodID_GetSupportedCurrencies,
				Handler:    _CurrencyService_GetSupportedCurrencies_Handler,
			},
			CurrencyService_MethodID_Convert: {
				MethodName: "Convert",
				MethodID:   CurrencyService_MethodID_Convert,
				Handler:    _CurrencyService_Convert_Handler,
			},
		},
	}, srv)
}

func _CurrencyService_GetSupportedCurrencies_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(EmptyUser)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CurrencyServiceServer).GetSupportedCurrencies(ctx, req.Payload.(*EmptyUser))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

func _CurrencyService_Convert_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(CurrencyConversionRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CurrencyServiceServer).Convert(ctx, req.Payload.(*CurrencyConversionRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for PaymentService
const (
	PaymentService_MethodID_Charge = 1
)

// Method name <-> ID mappings for PaymentService
var PaymentService_methodNameToID = map[string]uint32{
	"Charge": PaymentService_MethodID_Charge,
}

var PaymentService_methodIDToName = map[uint32]string{
	PaymentService_MethodID_Charge: "Charge",
}

// PaymentServiceClient is the client API for PaymentService service.
type PaymentServiceClient interface {
	Charge(ctx context.Context, req *ChargeRequest) (*ChargeResponse, error)
}

type arpcPaymentServiceClient struct {
	client *rpc.Client
}

func NewPaymentServiceClient(client *rpc.Client) PaymentServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("PaymentService", ServiceID_PaymentService, PaymentService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcPaymentServiceClient{client: client}
}

func (c *arpcPaymentServiceClient) Charge(ctx context.Context, req *ChargeRequest) (*ChargeResponse, error) {
	resp := new(ChargeResponse)
	if err := c.client.Call(ctx, "PaymentService", "Charge", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type PaymentServiceServer interface {
	Charge(ctx context.Context, req *ChargeRequest) (*ChargeResponse, context.Context, error)
}

func RegisterPaymentServiceServer(s *rpc.Server, srv PaymentServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "PaymentService",
		ServiceID:   ServiceID_PaymentService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			PaymentService_MethodID_Charge: {
				MethodName: "Charge",
				MethodID:   PaymentService_MethodID_Charge,
				Handler:    _PaymentService_Charge_Handler,
			},
		},
	}, srv)
}

func _PaymentService_Charge_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(ChargeRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(PaymentServiceServer).Charge(ctx, req.Payload.(*ChargeRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for EmailService
const (
	EmailService_MethodID_SendOrderConfirmation = 1
)

// Method name <-> ID mappings for EmailService
var EmailService_methodNameToID = map[string]uint32{
	"SendOrderConfirmation": EmailService_MethodID_SendOrderConfirmation,
}

var EmailService_methodIDToName = map[uint32]string{
	EmailService_MethodID_SendOrderConfirmation: "SendOrderConfirmation",
}

// EmailServiceClient is the client API for EmailService service.
type EmailServiceClient interface {
	SendOrderConfirmation(ctx context.Context, req *SendOrderConfirmationRequest) (*Empty, error)
}

type arpcEmailServiceClient struct {
	client *rpc.Client
}

func NewEmailServiceClient(client *rpc.Client) EmailServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("EmailService", ServiceID_EmailService, EmailService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcEmailServiceClient{client: client}
}

func (c *arpcEmailServiceClient) SendOrderConfirmation(ctx context.Context, req *SendOrderConfirmationRequest) (*Empty, error) {
	resp := new(Empty)
	if err := c.client.Call(ctx, "EmailService", "SendOrderConfirmation", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type EmailServiceServer interface {
	SendOrderConfirmation(ctx context.Context, req *SendOrderConfirmationRequest) (*Empty, context.Context, error)
}

func RegisterEmailServiceServer(s *rpc.Server, srv EmailServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "EmailService",
		ServiceID:   ServiceID_EmailService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			EmailService_MethodID_SendOrderConfirmation: {
				MethodName: "SendOrderConfirmation",
				MethodID:   EmailService_MethodID_SendOrderConfirmation,
				Handler:    _EmailService_SendOrderConfirmation_Handler,
			},
		},
	}, srv)
}

func _EmailService_SendOrderConfirmation_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(SendOrderConfirmationRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(EmailServiceServer).SendOrderConfirmation(ctx, req.Payload.(*SendOrderConfirmationRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for CheckoutService
const (
	CheckoutService_MethodID_PlaceOrder = 1
)

// Method name <-> ID mappings for CheckoutService
var CheckoutService_methodNameToID = map[string]uint32{
	"PlaceOrder": CheckoutService_MethodID_PlaceOrder,
}

var CheckoutService_methodIDToName = map[uint32]string{
	CheckoutService_MethodID_PlaceOrder: "PlaceOrder",
}

// CheckoutServiceClient is the client API for CheckoutService service.
type CheckoutServiceClient interface {
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*PlaceOrderResponse, error)
}

type arpcCheckoutServiceClient struct {
	client *rpc.Client
}

func NewCheckoutServiceClient(client *rpc.Client) CheckoutServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("CheckoutService", ServiceID_CheckoutService, CheckoutService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcCheckoutServiceClient{client: client}
}

func (c *arpcCheckoutServiceClient) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*PlaceOrderResponse, error) {
	resp := new(PlaceOrderResponse)
	if err := c.client.Call(ctx, "CheckoutService", "PlaceOrder", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type CheckoutServiceServer interface {
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*PlaceOrderResponse, context.Context, error)
}

func RegisterCheckoutServiceServer(s *rpc.Server, srv CheckoutServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "CheckoutService",
		ServiceID:   ServiceID_CheckoutService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			CheckoutService_MethodID_PlaceOrder: {
				MethodName: "PlaceOrder",
				MethodID:   CheckoutService_MethodID_PlaceOrder,
				Handler:    _CheckoutService_PlaceOrder_Handler,
			},
		},
	}, srv)
}

func _CheckoutService_PlaceOrder_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(PlaceOrderRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(CheckoutServiceServer).PlaceOrder(ctx, req.Payload.(*PlaceOrderRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}

// Method IDs for AdService
const (
	AdService_MethodID_GetAds = 1
)

// Method name <-> ID mappings for AdService
var AdService_methodNameToID = map[string]uint32{
	"GetAds": AdService_MethodID_GetAds,
}

var AdService_methodIDToName = map[uint32]string{
	AdService_MethodID_GetAds: "GetAds",
}

// AdServiceClient is the client API for AdService service.
type AdServiceClient interface {
	GetAds(ctx context.Context, req *AdRequest) (*AdResponse, error)
}

type arpcAdServiceClient struct {
	client *rpc.Client
}

func NewAdServiceClient(client *rpc.Client) AdServiceClient {
	// Create and register service registry
	registry := rpc.NewServiceRegistry()
	registry.RegisterService("AdService", ServiceID_AdService, AdService_methodNameToID)
	client.SetServiceRegistry(registry)
	return &arpcAdServiceClient{client: client}
}

func (c *arpcAdServiceClient) GetAds(ctx context.Context, req *AdRequest) (*AdResponse, error) {
	resp := new(AdResponse)
	if err := c.client.Call(ctx, "AdService", "GetAds", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type AdServiceServer interface {
	GetAds(ctx context.Context, req *AdRequest) (*AdResponse, context.Context, error)
}

func RegisterAdServiceServer(s *rpc.Server, srv AdServiceServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "AdService",
		ServiceID:   ServiceID_AdService,
		ServiceImpl: srv,
		MethodsByID: map[uint32]*rpc.MethodDesc{
			AdService_MethodID_GetAds: {
				MethodName: "GetAds",
				MethodID:   AdService_MethodID_GetAds,
				Handler:    _AdService_GetAds_Handler,
			},
		},
	}, srv)
}

func _AdService_GetAds_Handler(srv any, ctx context.Context, dec func(any) error, req *element.RPCRequest, chain *element.RPCElementChain) (*element.RPCResponse, context.Context, error) {
	req.Payload = new(AdRequest)
	if err := dec(req.Payload); err != nil {
		return nil, ctx, err
	}
	req, ctx, err := chain.ProcessRequest(ctx, req)
	if err != nil {
		return nil, ctx, err
	}
	result, ctx, err := srv.(AdServiceServer).GetAds(ctx, req.Payload.(*AdRequest))
	if err != nil {
		return nil, ctx, err
	}
	resp := &element.RPCResponse{
		ID:     req.ID,
		Result: result,
	}
	resp, ctx, err = chain.ProcessResponse(ctx, resp)
	if err != nil {
		return nil, ctx, err
	}
	return resp, ctx, err
}
