// Code generated by protoc-gen-symphony-hybrid. DO NOT EDIT.
package onlineboutique

import (
	"encoding/binary"
	"fmt"

	"google.golang.org/protobuf/proto"
)

func (m *CartItem) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &CartItem{
		ProductId: m.ProductId,
		Quantity:  m.Quantity,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *CartItem) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &CartItem{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.ProductId = privateMsg.ProductId
		m.Quantity = privateMsg.Quantity
	}
	return nil
}

func (m *AddItemRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &AddItemRequest{
		UserId: m.UserId,
		Item:   m.Item,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *AddItemRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &AddItemRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
		m.Item = privateMsg.Item
	}
	return nil
}

func (m *EmptyCartRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &EmptyCartRequest{
		UserId: m.UserId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *EmptyCartRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &EmptyCartRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
	}
	return nil
}

func (m *GetCartRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &GetCartRequest{
		UserId: m.UserId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *GetCartRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &GetCartRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
	}
	return nil
}

func (m *Cart) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &Cart{
		UserId: m.UserId,
		Items:  m.Items,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *Cart) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &Cart{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
		m.Items = privateMsg.Items
	}
	return nil
}

func (m *Empty) MarshalSymphonyHybrid() ([]byte, error) {
	// Empty message - public segment with header only, empty private segment
	buf := make([]byte, 13)                     // 1 version + 12 reserved
	buf[0] = 0x01                               // public version
	binary.LittleEndian.PutUint32(buf[1:5], 13) // offset_to_private (no private segment)
	// service_name and method_name stay 0
	return buf, nil
}

func (m *Empty) UnmarshalSymphonyHybrid(data []byte) error {
	// Empty message - just validate header
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}
	return nil
}

func (m *EmptyUser) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &EmptyUser{
		UserId: m.UserId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *EmptyUser) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &EmptyUser{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
	}
	return nil
}

func (m *ListRecommendationsRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ListRecommendationsRequest{
		UserId:     m.UserId,
		ProductIds: m.ProductIds,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ListRecommendationsRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ListRecommendationsRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
		m.ProductIds = privateMsg.ProductIds
	}
	return nil
}

func (m *ListRecommendationsResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ListRecommendationsResponse{
		ProductIds: m.ProductIds,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ListRecommendationsResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ListRecommendationsResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.ProductIds = privateMsg.ProductIds
	}
	return nil
}

func (m *Product) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &Product{
		Id:          m.Id,
		Name:        m.Name,
		Description: m.Description,
		Picture:     m.Picture,
		PriceUsd:    m.PriceUsd,
		Categories:  m.Categories,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *Product) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &Product{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Id = privateMsg.Id
		m.Name = privateMsg.Name
		m.Description = privateMsg.Description
		m.Picture = privateMsg.Picture
		m.PriceUsd = privateMsg.PriceUsd
		m.Categories = privateMsg.Categories
	}
	return nil
}

func (m *ListProductsResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ListProductsResponse{
		Products: m.Products,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ListProductsResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ListProductsResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Products = privateMsg.Products
	}
	return nil
}

func (m *GetProductRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &GetProductRequest{
		Id: m.Id,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *GetProductRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &GetProductRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Id = privateMsg.Id
	}
	return nil
}

func (m *SearchProductsRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &SearchProductsRequest{
		Query: m.Query,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *SearchProductsRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &SearchProductsRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Query = privateMsg.Query
	}
	return nil
}

func (m *SearchProductsResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &SearchProductsResponse{
		Results: m.Results,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *SearchProductsResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &SearchProductsResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Results = privateMsg.Results
	}
	return nil
}

func (m *GetQuoteRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &GetQuoteRequest{
		Address: m.Address,
		Items:   m.Items,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *GetQuoteRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &GetQuoteRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Address = privateMsg.Address
		m.Items = privateMsg.Items
	}
	return nil
}

func (m *GetQuoteResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &GetQuoteResponse{
		CostUsd: m.CostUsd,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *GetQuoteResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &GetQuoteResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.CostUsd = privateMsg.CostUsd
	}
	return nil
}

func (m *ShipOrderRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ShipOrderRequest{
		Address: m.Address,
		Items:   m.Items,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ShipOrderRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ShipOrderRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Address = privateMsg.Address
		m.Items = privateMsg.Items
	}
	return nil
}

func (m *ShipOrderResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ShipOrderResponse{
		TrackingId: m.TrackingId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ShipOrderResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ShipOrderResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.TrackingId = privateMsg.TrackingId
	}
	return nil
}

func (m *Address) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &Address{
		StreetAddress: m.StreetAddress,
		City:          m.City,
		State:         m.State,
		Country:       m.Country,
		ZipCode:       m.ZipCode,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *Address) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &Address{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.StreetAddress = privateMsg.StreetAddress
		m.City = privateMsg.City
		m.State = privateMsg.State
		m.Country = privateMsg.Country
		m.ZipCode = privateMsg.ZipCode
	}
	return nil
}

func (m *Money) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &Money{
		CurrencyCode: m.CurrencyCode,
		Units:        m.Units,
		Nanos:        m.Nanos,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *Money) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &Money{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.CurrencyCode = privateMsg.CurrencyCode
		m.Units = privateMsg.Units
		m.Nanos = privateMsg.Nanos
	}
	return nil
}

func (m *GetSupportedCurrenciesResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &GetSupportedCurrenciesResponse{
		CurrencyCodes: m.CurrencyCodes,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *GetSupportedCurrenciesResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &GetSupportedCurrenciesResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.CurrencyCodes = privateMsg.CurrencyCodes
	}
	return nil
}

func (m *CurrencyConversionRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &CurrencyConversionRequest{
		From:   m.From,
		ToCode: m.ToCode,
		UserId: m.UserId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *CurrencyConversionRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &CurrencyConversionRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.From = privateMsg.From
		m.ToCode = privateMsg.ToCode
		m.UserId = privateMsg.UserId
	}
	return nil
}

func (m *CreditCardInfo) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &CreditCardInfo{
		CreditCardNumber:          m.CreditCardNumber,
		CreditCardCvv:             m.CreditCardCvv,
		CreditCardExpirationYear:  m.CreditCardExpirationYear,
		CreditCardExpirationMonth: m.CreditCardExpirationMonth,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *CreditCardInfo) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &CreditCardInfo{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.CreditCardNumber = privateMsg.CreditCardNumber
		m.CreditCardCvv = privateMsg.CreditCardCvv
		m.CreditCardExpirationYear = privateMsg.CreditCardExpirationYear
		m.CreditCardExpirationMonth = privateMsg.CreditCardExpirationMonth
	}
	return nil
}

func (m *ChargeRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ChargeRequest{
		Amount:     m.Amount,
		CreditCard: m.CreditCard,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ChargeRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ChargeRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Amount = privateMsg.Amount
		m.CreditCard = privateMsg.CreditCard
	}
	return nil
}

func (m *ChargeResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &ChargeResponse{
		TransactionId: m.TransactionId,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *ChargeResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &ChargeResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.TransactionId = privateMsg.TransactionId
	}
	return nil
}

func (m *OrderItem) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &OrderItem{
		Item: m.Item,
		Cost: m.Cost,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *OrderItem) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &OrderItem{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Item = privateMsg.Item
		m.Cost = privateMsg.Cost
	}
	return nil
}

func (m *OrderResult) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &OrderResult{
		OrderId:            m.OrderId,
		ShippingTrackingId: m.ShippingTrackingId,
		ShippingCost:       m.ShippingCost,
		ShippingAddress:    m.ShippingAddress,
		Items:              m.Items,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *OrderResult) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &OrderResult{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.OrderId = privateMsg.OrderId
		m.ShippingTrackingId = privateMsg.ShippingTrackingId
		m.ShippingCost = privateMsg.ShippingCost
		m.ShippingAddress = privateMsg.ShippingAddress
		m.Items = privateMsg.Items
	}
	return nil
}

func (m *SendOrderConfirmationRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &SendOrderConfirmationRequest{
		Email: m.Email,
		Order: m.Order,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *SendOrderConfirmationRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &SendOrderConfirmationRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Email = privateMsg.Email
		m.Order = privateMsg.Order
	}
	return nil
}

func (m *PlaceOrderRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &PlaceOrderRequest{
		UserId:       m.UserId,
		UserCurrency: m.UserCurrency,
		Address:      m.Address,
		Email:        m.Email,
		CreditCard:   m.CreditCard,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *PlaceOrderRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &PlaceOrderRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
		m.UserCurrency = privateMsg.UserCurrency
		m.Address = privateMsg.Address
		m.Email = privateMsg.Email
		m.CreditCard = privateMsg.CreditCard
	}
	return nil
}

func (m *PlaceOrderResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &PlaceOrderResponse{
		Order: m.Order,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *PlaceOrderResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &PlaceOrderResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Order = privateMsg.Order
	}
	return nil
}

func (m *AdRequest) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &AdRequest{
		UserId:      m.UserId,
		ContextKeys: m.ContextKeys,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *AdRequest) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &AdRequest{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.UserId = privateMsg.UserId
		m.ContextKeys = privateMsg.ContextKeys
	}
	return nil
}

func (m *AdResponse) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &AdResponse{
		Ads: m.Ads,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *AdResponse) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &AdResponse{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.Ads = privateMsg.Ads
	}
	return nil
}

func (m *Ad) MarshalSymphonyHybrid() ([]byte, error) {
	// Calculate public segment size
	publicSegmentSize := 13
	publicSegmentSize += 0 // public table

	// Marshal private fields using protobuf
	privateMsg := &Ad{
		RedirectUrl: m.RedirectUrl,
		Text:        m.Text,
	}
	privateData, err := proto.Marshal(privateMsg)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal private segment: %w", err)
	}

	// Calculate total size
	totalSize := publicSegmentSize + len(privateData)
	buf := make([]byte, totalSize)

	// Write header
	buf[0] = 0x01                                                      // version byte
	binary.LittleEndian.PutUint32(buf[1:5], uint32(publicSegmentSize)) // offset_to_private
	binary.LittleEndian.PutUint32(buf[5:9], 0)                         // service_id
	binary.LittleEndian.PutUint32(buf[9:13], 0)                        // method_id

	// Write public segment (Symphony format)
	publicTableStart := 13
	publicPayloadStart := publicTableStart + 0
	publicPayloadOffset := 0
	dataLen := 0
	_ = publicPayloadStart
	_ = publicPayloadOffset
	_ = dataLen

	// Write private segment (Protobuf format)
	copy(buf[publicSegmentSize:], privateData)

	return buf, nil
}

func (m *Ad) UnmarshalSymphonyHybrid(data []byte) error {
	if len(data) < 13 {
		return fmt.Errorf("invalid data: too short")
	}

	// Validate public segment version
	if data[0] != 0x01 {
		return fmt.Errorf("invalid data: wrong public version")
	}

	// Read header
	offsetToPrivate := int(binary.LittleEndian.Uint32(data[1:5]))
	// service_name := binary.LittleEndian.Uint32(data[5:9])  // not used yet
	// method_name := binary.LittleEndian.Uint32(data[9:13])  // not used yet

	payloadOffset := 0
	_ = payloadOffset
	dataLen := 0
	_ = dataLen
	count := 0
	_ = count
	currentOffset := 0
	_ = currentOffset

	// === PUBLIC FIELDS (Symphony format) ===
	publicTableStart := 13
	_ = publicTableStart
	// === PRIVATE FIELDS (Protobuf format) ===
	if offsetToPrivate < len(data) {
		privateData := data[offsetToPrivate:]
		privateMsg := &Ad{}
		if err := proto.Unmarshal(privateData, privateMsg); err != nil {
			return fmt.Errorf("failed to unmarshal private segment: %w", err)
		}
		m.RedirectUrl = privateMsg.RedirectUrl
		m.Text = privateMsg.Text
	}
	return nil
}
