// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Ad struct {
	_tab flatbuffers.Table
}

func GetRootAsAd(buf []byte, offset flatbuffers.UOffsetT) *Ad {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Ad{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Ad) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Ad) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Ad) RedirectUrl() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Ad) Text() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AdAddRedirectUrl(builder *flatbuffers.Builder, redirectUrl flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(redirectUrl), 0)
}
func AdAddText(builder *flatbuffers.Builder, text flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(text), 0)
}
func AdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
