// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddItemRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAddItemRequest(buf []byte, offset flatbuffers.UOffsetT) *AddItemRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddItemRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AddItemRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddItemRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddItemRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AddItemRequest) Item(obj *CartItem) *CartItem {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CartItem)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func AddItemRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AddItemRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func AddItemRequestAddItem(builder *flatbuffers.Builder, item flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(item), 0)
}
func AddItemRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
