// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AdResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAdResponse(buf []byte, offset flatbuffers.UOffsetT) *AdResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AdResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AdResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AdResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AdResponse) Ads(obj *Ad, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AdResponse) AdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AdResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AdResponseAddAds(builder *flatbuffers.Builder, ads flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ads), 0)
}
func AdResponseStartAdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AdResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
