// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CartItem struct {
	_tab flatbuffers.Table
}

func GetRootAsCartItem(buf []byte, offset flatbuffers.UOffsetT) *CartItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CartItem{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CartItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CartItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CartItem) ProductId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CartItem) Quantity() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CartItem) MutateQuantity(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func CartItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CartItemAddProductId(builder *flatbuffers.Builder, productId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(productId), 0)
}
func CartItemAddQuantity(builder *flatbuffers.Builder, quantity int32) {
	builder.PrependInt32Slot(1, quantity, 0)
}
func CartItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
