// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChargeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsChargeRequest(buf []byte, offset flatbuffers.UOffsetT) *ChargeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChargeRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ChargeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChargeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChargeRequest) Amount(obj *Money) *Money {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Money)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ChargeRequest) CreditCard(obj *CreditCardInfo) *CreditCardInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CreditCardInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ChargeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ChargeRequestAddAmount(builder *flatbuffers.Builder, amount flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(amount), 0)
}
func ChargeRequestAddCreditCard(builder *flatbuffers.Builder, creditCard flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(creditCard), 0)
}
func ChargeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
