// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ChargeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsChargeResponse(buf []byte, offset flatbuffers.UOffsetT) *ChargeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ChargeResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ChargeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ChargeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ChargeResponse) TransactionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ChargeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ChargeResponseAddTransactionId(builder *flatbuffers.Builder, transactionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(transactionId), 0)
}
func ChargeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
