// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreditCardInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsCreditCardInfo(buf []byte, offset flatbuffers.UOffsetT) *CreditCardInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreditCardInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CreditCardInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreditCardInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreditCardInfo) CreditCardNumber() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CreditCardInfo) CreditCardCvv() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CreditCardInfo) MutateCreditCardCvv(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *CreditCardInfo) CreditCardExpirationYear() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CreditCardInfo) MutateCreditCardExpirationYear(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *CreditCardInfo) CreditCardExpirationMonth() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CreditCardInfo) MutateCreditCardExpirationMonth(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func CreditCardInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func CreditCardInfoAddCreditCardNumber(builder *flatbuffers.Builder, creditCardNumber flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(creditCardNumber), 0)
}
func CreditCardInfoAddCreditCardCvv(builder *flatbuffers.Builder, creditCardCvv int32) {
	builder.PrependInt32Slot(1, creditCardCvv, 0)
}
func CreditCardInfoAddCreditCardExpirationYear(builder *flatbuffers.Builder, creditCardExpirationYear int32) {
	builder.PrependInt32Slot(2, creditCardExpirationYear, 0)
}
func CreditCardInfoAddCreditCardExpirationMonth(builder *flatbuffers.Builder, creditCardExpirationMonth int32) {
	builder.PrependInt32Slot(3, creditCardExpirationMonth, 0)
}
func CreditCardInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
