// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CurrencyConversionRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCurrencyConversionRequest(buf []byte, offset flatbuffers.UOffsetT) *CurrencyConversionRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CurrencyConversionRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CurrencyConversionRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CurrencyConversionRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CurrencyConversionRequest) From(obj *Money) *Money {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Money)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *CurrencyConversionRequest) ToCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CurrencyConversionRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CurrencyConversionRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CurrencyConversionRequestAddFrom(builder *flatbuffers.Builder, from flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(from), 0)
}
func CurrencyConversionRequestAddToCode(builder *flatbuffers.Builder, toCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(toCode), 0)
}
func CurrencyConversionRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(userId), 0)
}
func CurrencyConversionRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
