// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Empty struct {
	_tab flatbuffers.Table
}

func GetRootAsEmpty(buf []byte, offset flatbuffers.UOffsetT) *Empty {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Empty{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Empty) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Empty) Table() flatbuffers.Table {
	return rcv._tab
}

func EmptyStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EmptyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
