// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type EmptyCartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsEmptyCartRequest(buf []byte, offset flatbuffers.UOffsetT) *EmptyCartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EmptyCartRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *EmptyCartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EmptyCartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EmptyCartRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EmptyCartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func EmptyCartRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func EmptyCartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
