// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetCartRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetCartRequest(buf []byte, offset flatbuffers.UOffsetT) *GetCartRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetCartRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetCartRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetCartRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetCartRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetCartRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetCartRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func GetCartRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
