// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetProductRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetProductRequest(buf []byte, offset flatbuffers.UOffsetT) *GetProductRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetProductRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetProductRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetProductRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetProductRequest) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetProductRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetProductRequestAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func GetProductRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
