// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetQuoteResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsGetQuoteResponse(buf []byte, offset flatbuffers.UOffsetT) *GetQuoteResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetQuoteResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetQuoteResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetQuoteResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetQuoteResponse) CostUsd(obj *Money) *Money {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Money)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func GetQuoteResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetQuoteResponseAddCostUsd(builder *flatbuffers.Builder, costUsd flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(costUsd), 0)
}
func GetQuoteResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
