// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListProductsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsListProductsResponse(buf []byte, offset flatbuffers.UOffsetT) *ListProductsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListProductsResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ListProductsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListProductsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListProductsResponse) Products(obj *Product, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *ListProductsResponse) ProductsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListProductsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ListProductsResponseAddProducts(builder *flatbuffers.Builder, products flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(products), 0)
}
func ListProductsResponseStartProductsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListProductsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
