// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListRecommendationsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsListRecommendationsRequest(buf []byte, offset flatbuffers.UOffsetT) *ListRecommendationsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListRecommendationsRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ListRecommendationsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListRecommendationsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListRecommendationsRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListRecommendationsRequest) ProductIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ListRecommendationsRequest) ProductIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ListRecommendationsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ListRecommendationsRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func ListRecommendationsRequestAddProductIds(builder *flatbuffers.Builder, productIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(productIds), 0)
}
func ListRecommendationsRequestStartProductIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ListRecommendationsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
