// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Money struct {
	_tab flatbuffers.Table
}

func GetRootAsMoney(buf []byte, offset flatbuffers.UOffsetT) *Money {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Money{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Money) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Money) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Money) CurrencyCode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Money) Units() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Money) MutateUnits(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Money) Nanos() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Money) MutateNanos(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func MoneyStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MoneyAddCurrencyCode(builder *flatbuffers.Builder, currencyCode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(currencyCode), 0)
}
func MoneyAddUnits(builder *flatbuffers.Builder, units int64) {
	builder.PrependInt64Slot(1, units, 0)
}
func MoneyAddNanos(builder *flatbuffers.Builder, nanos int32) {
	builder.PrependInt32Slot(2, nanos, 0)
}
func MoneyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
