// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type OrderItem struct {
	_tab flatbuffers.Table
}

func GetRootAsOrderItem(buf []byte, offset flatbuffers.UOffsetT) *OrderItem {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &OrderItem{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *OrderItem) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *OrderItem) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *OrderItem) Item(obj *CartItem) *CartItem {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CartItem)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *OrderItem) Cost(obj *Money) *Money {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Money)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func OrderItemStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func OrderItemAddItem(builder *flatbuffers.Builder, item flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(item), 0)
}
func OrderItemAddCost(builder *flatbuffers.Builder, cost flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(cost), 0)
}
func OrderItemEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
