// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlaceOrderRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsPlaceOrderRequest(buf []byte, offset flatbuffers.UOffsetT) *PlaceOrderRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlaceOrderRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PlaceOrderRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlaceOrderRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlaceOrderRequest) UserId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlaceOrderRequest) UserCurrency() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlaceOrderRequest) Address(obj *Address) *Address {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Address)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *PlaceOrderRequest) Email() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PlaceOrderRequest) CreditCard(obj *CreditCardInfo) *CreditCardInfo {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CreditCardInfo)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PlaceOrderRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PlaceOrderRequestAddUserId(builder *flatbuffers.Builder, userId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(userId), 0)
}
func PlaceOrderRequestAddUserCurrency(builder *flatbuffers.Builder, userCurrency flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(userCurrency), 0)
}
func PlaceOrderRequestAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(address), 0)
}
func PlaceOrderRequestAddEmail(builder *flatbuffers.Builder, email flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(email), 0)
}
func PlaceOrderRequestAddCreditCard(builder *flatbuffers.Builder, creditCard flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(creditCard), 0)
}
func PlaceOrderRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
