// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PlaceOrderResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsPlaceOrderResponse(buf []byte, offset flatbuffers.UOffsetT) *PlaceOrderResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PlaceOrderResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PlaceOrderResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PlaceOrderResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PlaceOrderResponse) Order(obj *OrderResult) *OrderResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OrderResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func PlaceOrderResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func PlaceOrderResponseAddOrder(builder *flatbuffers.Builder, order flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(order), 0)
}
func PlaceOrderResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
