// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SearchProductsResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsSearchProductsResponse(buf []byte, offset flatbuffers.UOffsetT) *SearchProductsResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SearchProductsResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SearchProductsResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SearchProductsResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SearchProductsResponse) Results(obj *Product, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SearchProductsResponse) ResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SearchProductsResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SearchProductsResponseAddResults(builder *flatbuffers.Builder, results flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(results), 0)
}
func SearchProductsResponseStartResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SearchProductsResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
