// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SearchProductsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSearchProductsRequest(buf []byte, offset flatbuffers.UOffsetT) *SearchProductsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SearchProductsRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SearchProductsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SearchProductsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SearchProductsRequest) Query() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SearchProductsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SearchProductsRequestAddQuery(builder *flatbuffers.Builder, query flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(query), 0)
}
func SearchProductsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
