// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SendOrderConfirmationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSendOrderConfirmationRequest(buf []byte, offset flatbuffers.UOffsetT) *SendOrderConfirmationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendOrderConfirmationRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SendOrderConfirmationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendOrderConfirmationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendOrderConfirmationRequest) Email() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SendOrderConfirmationRequest) Order(obj *OrderResult) *OrderResult {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(OrderResult)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SendOrderConfirmationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SendOrderConfirmationRequestAddEmail(builder *flatbuffers.Builder, email flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(email), 0)
}
func SendOrderConfirmationRequestAddOrder(builder *flatbuffers.Builder, order flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(order), 0)
}
func SendOrderConfirmationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
