// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package proto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ShipOrderResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsShipOrderResponse(buf []byte, offset flatbuffers.UOffsetT) *ShipOrderResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ShipOrderResponse{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ShipOrderResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ShipOrderResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ShipOrderResponse) TrackingId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ShipOrderResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ShipOrderResponseAddTrackingId(builder *flatbuffers.Builder, trackingId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(trackingId), 0)
}
func ShipOrderResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
